steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', '$_IMAGE:latest', '.']
- name: 'gcr.io/cloud-builders/docker'
  env:
    - TAG=$TAG_NAME
    - IMAGE=$_IMAGE
  entrypoint: /bin/bash
  args: ['-c', 'docker tag $$IMAGE:latest $$IMAGE:${TAG:-latest}']
substitutions:
    _IMAGE: gcr.io/binx-io/instruqt-cloud-client
