steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', '$_IMAGE:latest', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['tag', '$_IMAGE:latest', '$_IMAGE:$SHORT_SHA']
substitutions:
    _IMAGE: gcr.io/binx-io/instruqt/cloud-client
images:
  - ${_IMAGE}:latest
  - ${_IMAGE}:${SHORT_SHA}
