steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/${PROJECT_ID}/instruqt/cloud-client:latest', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['tag', 'gcr.io/${PROJECT_ID}/instruqt/cloud-client:latest', 'gcr.io/${PROJECT_ID}/instruqt/cloud-client:${TAG_NAME:-latest}']
images:
- gcr.io/${PROJECT_ID}/instruqt/cloud-client:latest
- gcr.io/${PROJECT_ID}/instruqt/cloud-client:${TAG_NAME:-latest}
